services:
  mongo-shard1-1:
    image: mongo:7
    container_name: mongo-shard1-1
    command: mongod --shardsvr --replSet mongo-shard1-rs --port 27017 --bind_ip localhost,mongo-shard1-1
    ports:
      - "27101:27017"
    networks:
      - mongodb-network
    restart: always

  mongo-shard1-2:
    image: mongo:7
    container_name: mongo-shard1-2
    command: mongod --shardsvr --replSet mongo-shard1-rs --port 27017 --bind_ip localhost,mongo-shard1-2
    ports:
      - "27102:27017"
    networks:
      - mongodb-network
    restart: always

  mongo-shard1-3:
    image: mongo:7
    container_name: mongo-shard1-3
    command: mongod --shardsvr --replSet mongo-shard1-rs --port 27017 --bind_ip localhost,mongo-shard1-3
    ports:
      - "27103:27017"
    networks:
      - mongodb-network
    restart: always

networks:
  mongodb-network:
    driver: bridge