services:
  mongo-shard2-1:
    image: mongo:7
    container_name: mongo-shard2-1
    command: mongod --shardsvr --replSet mongo-shard2-rs --port 27017 --bind_ip localhost,mongo-shard2-1
    ports:
      - "27201:27017"
    networks:
      - mongodb-network
    restart: always

  mongo-shard2-2:
    image: mongo:7
    container_name: mongo-shard2-2
    command: mongod --shardsvr --replSet mongo-shard2-rs --port 27017 --bind_ip localhost,mongo-shard2-2
    ports:
      - "27202:27017"
    networks:
      - mongodb-network
    restart: always

  mongo-shard2-3:
    image: mongo:7
    container_name: mongo-shard2-3
    command: mongod --shardsvr --replSet mongo-shard2-rs --port 27017 --bind_ip localhost,mongo-shard2-3
    ports:
      - "27203:27017"
    networks:
      - mongodb-network
    restart: always

networks:
  mongodb-network:
    driver: bridge
